Readme updates.
ketch-sdk/ketch-samples pull request #23
Opened 2022-11-23 10:11 UTC by anton-lyfar

Changes:
- Removed readme in ios-samples directory
- Added readme for SwiftUI and Storyboard integration in corresponding folders.

2022-11-28 22:50 UTC, webdevbyjoss approved these changes
LGTM

2022-11-29 05:04 UTC, OnyxPrime commented on ketch-ios/iOS Ketch Pref Center using SwiftUI/README.md
> +                        propertyName: "website_smart_tag",
Please update `orgCode` and `propertyName` values to use placeholders, like in the Storyboard README.

2022-11-29 05:14 UTC, OnyxPrime requested changes
Please resolve comments

2022-11-29 13:37 UTC, OnyxPrime approved these changes

2022-11-29 13:37 UTC, merged